// cursos-frameworks/aprendiendo-vue/src/components/Sidebar.vue
<template>
  <aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
      <h3>Puedes hacer esto</h3>
      <a href="#" class="btn btn-success">Crear artículo</a>
    </div>

    <div id="search" class="sidebar-item">
      <h3>Buscador</h3>
      <p>Encuentra el artículo que buscas</p>
      <form>
        <input type="text" name="search" />
        <input type="submit" value="Buscar" class="btn" />
      </form>
    </div>
  </aside>
</template>

<script>
export default {
  name: "Sidebar",
};
</script>

// cursos-frameworks/AprendiendoAngular/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
//importamos cosas de router y servicios
import {Router, ActivatedRoute, Params} from '@angular/router';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {

  //lo que pasamos a la ruta de redireccion
  public searchString: string;

  constructor(
    private _router: Router,
    private _route: ActivatedRoute
  ) { }

  ngOnInit(): void {
  }

  //metodo para buscar articulos por formulario
  goSearch(){
    this._router.navigate(['buscar', this.searchString]);
  }

}

<aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
        <h3>Puedes hacer esto</h3>
        <a [routerLink]="['/blog/crear']" class="btn btn-success">Crear artículo</a>
    </div>

    <div id="search" class="sidebar-item">
        <h3>Buscador</h3>
        <p>Encuentra el artículo que buscas</p>
        <!--negSubmit nos permite añadir metodos a nuestro formulario para añadir funcionalidades-->
        <form #searchForm="ngForm" (ngSubmit)="goSearch()">
            <input type="text" name="search" [(ngModel)]="searchString"/>
            <input type="submit" value="Buscar" class="btn" />
        </form>
    </div>
</aside>
<div class="clearfix"></div>
